### ISSUE TITLE
Add coveralls.

### ISSUE THREAD

**Issue by moteus** [ignacio/lua-appveyor-example#18]
Now master version of luacov-coveralls supports appveyor.
So it possible use it as `luarocks show luacov-coveralls || luarocks install luacov-coveralls --server=https://luarocks.org/dev` for test.
But because in rocspec it has lua-cjson as deps it has problem with installation.
In fact luacov-coveralls cat works also with `dkjson`. Also lua-path under windows require `bit32` library on Lua 5.1.
So result install for now can be look like.

```yml
before_test:
  - luarocks show luacov || luarocks install luacov

after_test:
  - if "%LUA_VER:~0,3%"=="5.1" (luarocks show bit32 || luarocks install bit32)
  - luarocks show dkjson || luarocks install dkjson
  - luarocks show luafilesystem || luarocks install luafilesystem
  - luarocks show lua-path || luarocks install lua-path
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls --server=https://luarocks.org/dev --deps-mode=none
  - luacov-coveralls -v
```
